language: node_js
node_js:
- '0.10'
branches:
  only:
  - develop
  - master
  - /^pre-release-v[0-9\.]+$/
before_install:
  - git config --global user.email "ci@cork-labs.org"
  - git config --global user.name "Travis CI"
script:
  - git remote set-url origin "https://${GH_TOKEN}@github.com/andrezero/load-grunt-config-data.git"
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://${GH_TOKEN}:@github.com" > .git/credentials
  - bin/ci.js
env:
  global:
    secure: UIlf2PhFv6Is9GA0iJyS8VOuxDVYt+l+W65l+FdEkXpm9upGZZvZcA/69S6R65SsD9fCR9OQGPtNgUT7U813EgiM2EcV843xT3yiZJ8SgNA1E/Unq0xOGk7JddvbF17EzMm6waELf5Dqr1UKsGstdRm6w7KYdBBYaSe3Q0fgJe8=
