language: node_js
node_js:
- '0.10'
branches:
  only:
  - develop
  - master
before_install:
- git config --global user.email "ci@cork-labs.org"
- git config --global user.name "Travis CI"
- git config --global push.default matching
script:
- git remote set-url origin "https://${GH_TOKEN}@github.com/andrezero/load-grunt-config-data.git"
- git config credential.helper "store --file=.git/credentials"
- echo "https://${GH_TOKEN}:@github.com" > .git/credentials
- bin/ci.js
env:
  global:
  - secure: eNuvFB8L/oXvys98y1Av2B0JLGb68kLFSI+dbOdlV4HWQTQ4yLJ8Fu7cAboi0G+oKCj7C2FCBVAGy5P3Ga0guhWRxfOayIN4ZK+Tc0rbX546t50p79D+5DwzTlxg66cCcIFLTwd00tGLIvyx5329DOq9yuyGBU3YQvyLF2AILS0=
